FROM golang:alpine3.12 AS builder
ENV GOPROXY="https://goproxy.cn,direct"
COPY . $GOPATH/gocron
RUN cd $GOPATH/gocron/worker/main/ && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o worker && rm -rf main.go

FROM centos
COPY --from=builder /go/gocron/worker/main /app/
CMD ["/app/worker", "--config=/app/config.json"]
