# etcd 集群 & mongodb
version: '3'

services:
    etcd1:
        image: quay.io/coreos/etcd
        command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
        container_name: etcd1
        volumes:
            - etcd-data1:/etcd-data
        networks:
            - cron-net

    etcd2:
        image: quay.io/coreos/etcd
        command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
        container_name: etcd2
        volumes:
            - etcd-data2:/etcd-data
        networks:
            - cron-net

    etcd3:
        image: quay.io/coreos/etcd
        command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
        container_name: etcd3
        volumes:
            - etcd-data3:/etcd-data
        networks:
            - cron-net

    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - mongodb-data:/data
        networks:
            - cron-net

    gocron-master:
        build:
            context: ./
            dockerfile: Dockerfile.master
        container_name: gocron-master
        depends_on:
            - etcd1
            - etcd2
            - etcd3
            - mongodb

        networks:
            - cron-net
        ports:
            - 8070:8070
        environment:
            ETCD_N1: "etcd1:2379"
            ETCD_N2: "etcd2:2379"
            ETCD_N3: "etcd3:2379"
            MONGODB: "mongodb:27017"

    gocron-worker:
        build:
            context: ./
            dockerfile: ./Dockerfile.worker
        container_name: gocron-worker
        depends_on:
            - etcd1
            - etcd2
            - etcd3
            - mongodb
        networks:
            - cron-net
        environment:
            ETCD_N1: "etcd1:2379"
            ETCD_N2: "etcd2:2379"
            ETCD_N3: "etcd3:2379"
            MONGODB: "mongodb:27017"

networks:
    cron-net:
        driver: bridge

volumes:
    etcd-data1:
    etcd-data2:
    etcd-data3:
    mongodb-data: